<a href="https://colab.research.google.com/github/mayooueidat-uva/DS1002-S24/blob/main/Copy_of_Maya's_Copy_of_07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [ ]:
# Load pandas
import pandas as pd
import numpy as np

In [ ]:
# Load the data
from google.colab import drive
drive.mount('/content/drive')
url = 'https://docs.google.com/spreadsheets/d/1D4Myxarr85KCTAnIw2ek4R0dkzhnYhqL3r5ZI7Vs5XY/export?format=csv'
rideshare = pd.read_csv(url)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# show how many rows and columns are in this dataset
rideshare
# we have 25760 rows and 10 columns.

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14 minutes,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29 minutes,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [ ]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)

# first, i'll strip away 'minutes' from 'duration.'
# i'll also convert the data in our column to integers.
rideshare['duration'] = rideshare['duration'].str.strip(' minutes')
rideshare['duration'] = rideshare['duration'].astype('int')

In [ ]:
# Now display the datatypes in the updated dataframe
rideshare.dtypes
# the mission was a success sir!

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [ ]:
# just for me, i wish to show the actual updated dataframe.
rideshare

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [ ]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.

# the minimum ride duration seems to be one minute:
print(rideshare['duration'].min())

# the maximum ride duration seems to be 1372 minutes. may God help them
print(rideshare['duration'].max())

1
1372

In [ ]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
# useful resource: https://www.scaler.com/topics/pandas/pandas-query/
rideshare_short = rideshare.query('duration <= 60')

# i'm going to show this dataframe.
rideshare_short
# 25544 rows. less than 25760 rows. so we've successfully filtered the data.

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [ ]:
# Now show both the min and max values of the duration column for your new dataset.

# the minimum ride duration seems to be one minute, still:
print(rideshare_short['duration'].min())

# the maximum ride duration is quite obviously 60 minutes...
# ...i've banned any values larger than 60 from the 'duration' column.
print(rideshare_short['duration'].max())

1
60

In [ ]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
filter_tire = rideshare_short["tire_size"] == 26
rideshare_short_tire26 = rideshare_short[filter_tire]

# now let's show the dataframe with the modifications.
rideshare_short_tire26

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
...,...,...,...,...,...,...,...,...,...,...
25750,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,4372,2,1994,Male,26
25751,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,5246,1,1995,Male,26
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26

In [ ]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.


rideshare_short_tire26['user_gender'].value_counts()
# there are 2962 female riders, who used 26-inch wheeled rental bikes
# for their rentals of one hour or less.

Male      9625
Female    2962
Other      174
Name: user_gender, dtype: int64

2. Find the file `more-messy-data.csv` on Canvas and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [ ]:
# uploading the data
drive.mount('/content/drive')
url = 'https://docs.google.com/spreadsheets/d/16u-J-SfJmT7p3OLwIG8efRr7yHWCvZKKMWzFeocOS78/export?format=csv'
more_messy_data = pd.read_csv(url)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# i want to see how my data looks first.
more_messy_data
# ew

       id  sepal_length  sepal_width  petal_length petal_width     species
0       1           3.5          2.9           1.4         0.5   virginica
1       2           3.6          3.2           3.0         0.5      setosa
2       3           3.8          NaN           2.2         1.5      setosa
3       4           5.8          2.7           2.6         1.2   virginica
4       5           4.9          3.6           3.0         1.2   virginica
...   ...           ...          ...           ...         ...         ...
1311  412           NaN          3.6           2.9         0.5  Versicolor
1312  413           5.8          2.7           2.0         0.1  Versicolor
1313  414           3.3          3.7           1.3         2.8  Versicolor
1314  415           3.1          NaN           1.1         NaN  Versicolor
1315  416           4.3          2.5           1.3           1  Versicolor

[1316 rows x 6 columns]

In [ ]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
print(more_messy_data.duplicated().sum())

287

In [ ]:
# Next, remove all duplicate rows using Python.
more_messy_data = more_messy_data.drop_duplicates()

# making sure:
print(more_messy_data.duplicated().sum())

0

In [ ]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.

# i need help:
# https://saturncloud.io/blog/how-to-replace-nan-values-with-the-average-of-columns-in-pandas-dataframe/

# huh oh wow i'm running into a weird error in the petal_width column.
# before i follow through with this assignment, i gotta fix that.
more_messy_data.dtypes
# there's string values in that column? i wonder how to resolve this.

id                int64
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width      object
species          object
dtype: object

In [ ]:
# purging the strings from that column.
# any strings, i don't know how to deal with. so i'm turning them into NaN.
# https://stackoverflow.com/questions/39184442/pandas-dataframe-set-all-string-values-to-nan
# https://stackoverflow.com/questions/66093757/force-coerce-pandas-dataframe-column-to-int64-type

# using 'coerce' to turn strings into NaN
more_messy_data['petal_width'] = pd.to_numeric(more_messy_data['petal_width'], errors='coerce')

<ipython-input-157-26a8c3483b32>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_messy_data['petal_width'] = pd.to_numeric(more_messy_data['petal_width'], errors='coerce')

In [ ]:
# and NOW we replace NaN in each column with the means of each column.
# this will be followed through for the sepal_length, sepal_width...
# ...petal_length, and petal_width columns.

# finding the means
mean = more_messy_data.mean()

# replacing the means
more_messy_data.fillna(mean, inplace=True)

<ipython-input-158-d5bf432881da>:6: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean = more_messy_data.mean()
<ipython-input-158-d5bf432881da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_messy_data.fillna(mean, inplace=True)

In [ ]:
# new dataframe with NaNs replaced with means.

# oh dear that's so ugly that hurts my eyes
# let me see if i can make it look prettier.
# resource: https://www.freecodecamp.org/news/how-to-round-a-float-in-pandas/

# ...i'm rounding the values to the first decimal.
more_messy_data_round = more_messy_data.round(1)
# now, we show the new dataframe:
more_messy_data_round

       id  sepal_length  sepal_width  petal_length  petal_width     species
0       1           3.5          2.9           1.4          0.5   virginica
1       2           3.6          3.2           3.0          0.5      setosa
2       3           3.8          3.0           2.2          1.5      setosa
3       4           5.8          2.7           2.6          1.2   virginica
4       5           4.9          3.6           3.0          1.2   virginica
...   ...           ...          ...           ...          ...         ...
1311  412           4.5          3.6           2.9          0.5  Versicolor
1312  413           5.8          2.7           2.0          0.1  Versicolor
1313  414           3.3          3.7           1.3          2.8  Versicolor
1314  415           3.1          3.0           1.1          1.6  Versicolor
1315  416           4.3          2.5           1.3          1.0  Versicolor

[1029 rows x 6 columns]

In [ ]:
# Find any values in the dataframe that are still missing, and delete them.
less_messy_data_round = more_messy_data_round.dropna()
less_messy_data_round

       id  sepal_length  sepal_width  petal_length  petal_width     species
0       1           3.5          2.9           1.4          0.5   virginica
1       2           3.6          3.2           3.0          0.5      setosa
2       3           3.8          3.0           2.2          1.5      setosa
3       4           5.8          2.7           2.6          1.2   virginica
4       5           4.9          3.6           3.0          1.2   virginica
...   ...           ...          ...           ...          ...         ...
1311  412           4.5          3.6           2.9          0.5  Versicolor
1312  413           5.8          2.7           2.0          0.1  Versicolor
1313  414           3.3          3.7           1.3          2.8  Versicolor
1314  415           3.1          3.0           1.1          1.6  Versicolor
1315  416           4.3          2.5           1.3          1.0  Versicolor

[963 rows x 6 columns]

In [ ]:
# How many different species are there?
less_messy_data_round['species'].value_counts()
# there are three.
# everything else is a typo.
# if i count the typos, there are ten.

setosa        481
virginica     444
Versicolor     27
setoso          2
Virginia        2
Virginica       2
Setosa          2
Viginica        1
Setosan         1
versicolor      1
Name: species, dtype: int64

In [ ]:
# Clean up the 'species' variable so that there are exactly three different values.

# first, i'm going to correct the capitalisation on each of the strings.
less_messy_data_round["species"] = less_messy_data_round["species"].str.lower()

<ipython-input-162-5d059eb496b6>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  less_messy_data_round["species"] = less_messy_data_round["species"].str.lower()

In [ ]:
# How many different species are there NOW?
less_messy_data_round['species'].value_counts()

setosa        483
virginica     446
versicolor     28
setoso          2
virginia        2
viginica        1
setosan         1
Name: species, dtype: int64

In [ ]:
# okay. we have to correct typos now.
# we shall do so using a dictionary
mapping = {'setoso': 'setosa', 'virginia': 'virginica', 'viginica': 'virginica', 'setosan': 'setosa'}

# use `.replace`
less_messy_data_round['species'] = less_messy_data_round['species'].replace(mapping)
less_messy_data_round['species'].unique()

<ipython-input-164-5804d52a370f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  less_messy_data_round['species'] = less_messy_data_round['species'].replace(mapping)

array(['virginica', 'setosa', 'versicolor'], dtype=object)

In [ ]:
# HOW MANY DIFFERENT SPECIES ARE THERE NOW?????
less_messy_data_round['species'].value_counts()
# three! good! that's a relief! we're finished!

setosa        486
virginica     449
versicolor     28
Name: species, dtype: int64

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [ ]:
# Sample code for testing whether a string matches a regex
# extra resource i used: https://cs.lmu.edu/~ray/notes/regex/
# other resource: https://stackoverflow.com/questions/3617797/regex-to-match-only-letters
# yet another: https://stackoverflow.com/questions/42674717/regex-match-exactly-4-digits

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'aac+'
test = 'abcdefg'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

1. My regex for the Virginia license plates:

* [A-Z]{3}\d{4}$

In [ ]:
# MY regex for MY virginia license plates that I'M going to test.
# does it match?
exp = '[A-Z]{3}\d{4}$'
test = 'ZZZ1235'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

match!
<class 're.Match'>
True

In [ ]:
# does it match?
exp = '[A-Z]{3}\d{4}$'
test = 'MYA2004'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

match!
<class 're.Match'>
True

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'mya2004'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'MYA20004'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'MYA204'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'MAYA2004'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'MY2004'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [ ]:
# does it not match anything else?
exp = '[A-Z]{3}\d{4}$'
test = 'M2004YA'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False